version: '3.8'
services:
  dev:
    image: node:16.14
    user: "node"
    depends_on:
      - localstack
    working_dir: /app
    volumes:
      - ..:/app:cached
      - ~/.npmrc:/home/node/.npmrc:delegated
    command: sleep infinity

  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8021:8021"
    environment:
      - SERVICES=dynamodb,
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8021

    # volumes:
    #   - ./init-scripts:/docker-entrypoint-initaws.d
    #   - /var/run/docker.sock:/var/run/docker.sock
