# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release New package

on:
  push:
    branches:
      - main

  # release:
  #   types: [created]

  workflow_dispatch:
    inputs:
      create_new_release:
          required: true
          type: boolean
          description: "Set to TRUE to Confirm the creation of a new release"
    branches:
      - main

jobs:
  diagnotics:
    runs-on: ubuntu-latest
    steps:
      - name: Diagnostics
        run: |
           set -e
           echo "event_name=${{ github.event_name }}"
           echo "inputs.create_new_release=${{ inputs.create_new_release }}"

           echo -e "===================\n"
           echo -e "github.event\n"
           echo -e "${{toJSON(github.event)}}\n"

           echo -e "===================\n"
           echo -e "inputs\n"
           echo -e "${{toJSON(inputs)}}"

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: diagnotics
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@hyprnz'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HYPR_NPM_AUTH_TOKEN }}

      - name: Install Dependencies
        working-directory: .
        run: npm ci

      - name: Set Version
        run: |
          # BUILD_VERSION=1.0.$GITHUB_RUN_NUMBER
          BUILD_VERSION=1.0.0-beta.$GITHUB_RUN_NUMBER
          BUILD_DATE=$(date +%Y-%m-%dT%H:%MZ)
          npm version ${BUILD_VERSION} --no-git-tag-version
          echo -e "BUILD_VERSION=$BUILD_VERSION\nBUILD_DATE=$BUILD_DATE\nSHA:$GITHUB_SHA\nGITHUB_REF_NAME=$GITHUB_REF_NAME" >> ./version.txt

          echo "Verion File"
          cat ./version.txt

      - name: Build
        run: npm run build

      - name: Micro Test
        run: npm run test:micro

      - name: Integration Test
        run: |
          npm run docker:dev:up
          npm run docker:dev -- exec -T dev npm run test:integration
          npm run docker:dev:down

      - name: Publish Dry Run
        if: ${{ success() && inputs.create_new_release != true }}
        run: |
          npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HYPR_NPM_AUTH_TOKEN }}

      - name: Publish
        if: ${{ success() && github.event_name == 'workflow_dispatch' && inputs.create_new_release == true }}
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HYPR_NPM_AUTH_TOKEN }}




